// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
	require('../node_modules/@storybook/components/dist/ActionBar/ActionBar.stories');
	require('../node_modules/@storybook/components/dist/Badge/Badge.stories');
	require('../node_modules/@storybook/components/dist/Button/Button.stories');
	require('../node_modules/@storybook/components/dist/ScrollArea/ScrollArea.stories');
	require('../node_modules/@storybook/components/dist/blocks/ColorPalette.stories');
	require('../node_modules/@storybook/components/dist/blocks/Description.stories');
	require('../node_modules/@storybook/components/dist/blocks/DocsPage.stories');
	require('../node_modules/@storybook/components/dist/blocks/EmptyBlock.stories');
	require('../node_modules/@storybook/components/dist/blocks/IconGallery.stories');
	require('../node_modules/@storybook/components/dist/blocks/Preview.stories');
	require('../node_modules/@storybook/components/dist/blocks/PropsTable/PropRow.stories');
	require('../node_modules/@storybook/components/dist/blocks/PropsTable/PropsTable.stories');
	require('../node_modules/@storybook/components/dist/blocks/PropsTable/SectionRow.stories');
	require('../node_modules/@storybook/components/dist/blocks/Source.stories');
	require('../node_modules/@storybook/components/dist/blocks/Story.stories');
	require('../node_modules/@storybook/components/dist/blocks/Typeset.stories');
	require('../node_modules/@storybook/components/dist/brand/StorybookIcon.stories');
	require('../node_modules/@storybook/components/dist/brand/StorybookLogo.stories');
	require('../node_modules/@storybook/components/dist/form/form.stories');
	require('../node_modules/@storybook/components/dist/icon/icon.stories');
	require('../node_modules/@storybook/components/dist/placeholder/placeholder.stories');
	require('../node_modules/@storybook/components/dist/spaced/Spaced.stories');
	require('../node_modules/@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.stories');
	require('../node_modules/@storybook/components/dist/tabs/tabs.stories');
	require('../node_modules/@storybook/components/dist/tooltip/ListItem.stories');
	require('../node_modules/@storybook/components/dist/tooltip/Tooltip.stories');
	require('../node_modules/@storybook/components/dist/tooltip/TooltipLinkList.stories');
	require('../node_modules/@storybook/components/dist/tooltip/TooltipMessage.stories');
	require('../node_modules/@storybook/components/dist/tooltip/TooltipNote.stories');
	require('../node_modules/@storybook/components/dist/tooltip/WithTooltip.stories');
	require('../node_modules/@storybook/components/dist/typography/DocumentWrapper.stories');
	require('../node_modules/@storybook/components/dist/typography/link/link.stories');
	require('../node_modules/@storybook/components/dist/typography/typography.stories');
	require('../node_modules/@storybook/ui/dist/app.stories');
	require('../node_modules/@storybook/ui/dist/components/layout/layout.stories');
	require('../node_modules/@storybook/ui/dist/components/notifications/item.stories');
	require('../node_modules/@storybook/ui/dist/components/notifications/notifications.stories');
	require('../node_modules/@storybook/ui/dist/components/panel/panel.stories');
	require('../node_modules/@storybook/ui/dist/components/preview/iframe.stories');
	require('../node_modules/@storybook/ui/dist/components/preview/preview.stories');
	require('../node_modules/@storybook/ui/dist/components/sidebar/ListItemIcon.stories');
	require('../node_modules/@storybook/ui/dist/components/sidebar/Sidebar.stories');
	require('../node_modules/@storybook/ui/dist/components/sidebar/SidebarHeading.stories');
	require('../node_modules/@storybook/ui/dist/components/sidebar/SidebarItem.stories');
	require('../node_modules/@storybook/ui/dist/components/sidebar/SidebarSearch.stories');
	require('../node_modules/@storybook/ui/dist/components/sidebar/SidebarStories.stories');
	require('../node_modules/@storybook/ui/dist/components/sidebar/SidebarSubheading.stories');
	require('../node_modules/@storybook/ui/dist/containers/panel.stories');
	require('../node_modules/@storybook/ui/dist/settings/SettingsFooter.stories');
	require('../node_modules/@storybook/ui/dist/settings/about.stories');
	require('../node_modules/@storybook/ui/dist/settings/shortcuts.stories');
}

const stories = [
	'../node_modules/@storybook/components/dist/ActionBar/ActionBar.stories',
	'../node_modules/@storybook/components/dist/Badge/Badge.stories',
	'../node_modules/@storybook/components/dist/Button/Button.stories',
	'../node_modules/@storybook/components/dist/ScrollArea/ScrollArea.stories',
	'../node_modules/@storybook/components/dist/blocks/ColorPalette.stories',
	'../node_modules/@storybook/components/dist/blocks/Description.stories',
	'../node_modules/@storybook/components/dist/blocks/DocsPage.stories',
	'../node_modules/@storybook/components/dist/blocks/EmptyBlock.stories',
	'../node_modules/@storybook/components/dist/blocks/IconGallery.stories',
	'../node_modules/@storybook/components/dist/blocks/Preview.stories',
	'../node_modules/@storybook/components/dist/blocks/PropsTable/PropRow.stories',
	'../node_modules/@storybook/components/dist/blocks/PropsTable/PropsTable.stories',
	'../node_modules/@storybook/components/dist/blocks/PropsTable/SectionRow.stories',
	'../node_modules/@storybook/components/dist/blocks/Source.stories',
	'../node_modules/@storybook/components/dist/blocks/Story.stories',
	'../node_modules/@storybook/components/dist/blocks/Typeset.stories',
	'../node_modules/@storybook/components/dist/brand/StorybookIcon.stories',
	'../node_modules/@storybook/components/dist/brand/StorybookLogo.stories',
	'../node_modules/@storybook/components/dist/form/form.stories',
	'../node_modules/@storybook/components/dist/icon/icon.stories',
	'../node_modules/@storybook/components/dist/placeholder/placeholder.stories',
	'../node_modules/@storybook/components/dist/spaced/Spaced.stories',
	'../node_modules/@storybook/components/dist/syntaxhighlighter/syntaxhighlighter.stories',
	'../node_modules/@storybook/components/dist/tabs/tabs.stories',
	'../node_modules/@storybook/components/dist/tooltip/ListItem.stories',
	'../node_modules/@storybook/components/dist/tooltip/Tooltip.stories',
	'../node_modules/@storybook/components/dist/tooltip/TooltipLinkList.stories',
	'../node_modules/@storybook/components/dist/tooltip/TooltipMessage.stories',
	'../node_modules/@storybook/components/dist/tooltip/TooltipNote.stories',
	'../node_modules/@storybook/components/dist/tooltip/WithTooltip.stories',
	'../node_modules/@storybook/components/dist/typography/DocumentWrapper.stories',
	'../node_modules/@storybook/components/dist/typography/link/link.stories',
	'../node_modules/@storybook/components/dist/typography/typography.stories',
	'../node_modules/@storybook/ui/dist/app.stories',
	'../node_modules/@storybook/ui/dist/components/layout/layout.stories',
	'../node_modules/@storybook/ui/dist/components/notifications/item.stories',
	'../node_modules/@storybook/ui/dist/components/notifications/notifications.stories',
	'../node_modules/@storybook/ui/dist/components/panel/panel.stories',
	'../node_modules/@storybook/ui/dist/components/preview/iframe.stories',
	'../node_modules/@storybook/ui/dist/components/preview/preview.stories',
	'../node_modules/@storybook/ui/dist/components/sidebar/ListItemIcon.stories',
	'../node_modules/@storybook/ui/dist/components/sidebar/Sidebar.stories',
	'../node_modules/@storybook/ui/dist/components/sidebar/SidebarHeading.stories',
	'../node_modules/@storybook/ui/dist/components/sidebar/SidebarItem.stories',
	'../node_modules/@storybook/ui/dist/components/sidebar/SidebarSearch.stories',
	'../node_modules/@storybook/ui/dist/components/sidebar/SidebarStories.stories',
	'../node_modules/@storybook/ui/dist/components/sidebar/SidebarSubheading.stories',
	'../node_modules/@storybook/ui/dist/containers/panel.stories',
	'../node_modules/@storybook/ui/dist/settings/SettingsFooter.stories',
	'../node_modules/@storybook/ui/dist/settings/about.stories',
	'../node_modules/@storybook/ui/dist/settings/shortcuts.stories'
];

module.exports = {
  loadStories,
  stories,
};
